Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.Run "notepad.exe", 9
wscript.sleep 2000
wshshell.sendkeys "T"
wscript.sleep 30
wshshell.sendkeys "U"
wscript.sleep 30
wshshell.sendkeys " "
wscript.sleep 30
wshshell.sendkeys "V"
wscript.sleep 30
wshshell.sendkeys "I"
wscript.sleep 30
wshshell.sendkeys "E"
wscript.sleep 30
wshshell.sendkeys "N"
wscript.sleep 30
wshshell.sendkeys "S"
wscript.sleep 30
wshshell.sendkeys " "
wscript.sleep 30
wshshell.sendkeys "D"
wscript.sleep 30
wshshell.sendkeys "E"
wscript.sleep 30
wshshell.sendkeys " "
wscript.sleep 30
wshshell.sendkeys "T"
wscript.sleep 30
wshshell.sendkeys "E"
wscript.sleep 30
wshshell.sendkeys " "
wscript.sleep 30
wshshell.sendkeys "F"
wscript.sleep 30
wshshell.sendkeys "A"
wscript.sleep 30
wshshell.sendkeys "I"
wscript.sleep 30
wshshell.sendkeys "R"
wscript.sleep 30
wshshell.sendkeys "E"
wscript.sleep 30
wshshell.sendkeys " "
wscript.sleep 30
wshshell.sendkeys "M"
wscript.sleep 30
wshshell.sendkeys "R"
wscript.sleep 30
wshshell.sendkeys " "
wscript.sleep 30
wshshell.sendkeys "B"
wscript.sleep 30
wshshell.sendkeys "E"
wscript.sleep 30
wshshell.sendkeys "A"
wscript.sleep 30
wshshell.sendkeys "S"
wscript.sleep 30
wshshell.sendkeys "T"
wscript.sleep 30
wshshell.sendkeys "E"
wscript.sleep 30
wshshell.sendkeys "D"
wscript.sleep 30
wshshell.sendkeys "."
wscript.sleep 100
wshshell.sendkeys "^A"
wscript.sleep 100
wshshell.sendkeys "^C"
wscript.sleep 100
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 30
wshshell.sendkeys "^V"
wshshell.sendkeys "{ENTER}"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
wscript.sleep 100
wshshell.sendkeys "GZYM LE MEILLEUR"
wscript.sleep 10
wshshell.sendkeys "{ENTER}"
wscript.sleep 10
wshshell.sendkeys "#CPF"
wscript.sleep 100
wshshell.sendkeys "%{F4}"
wscript.sleep 100
wshshell.sendkeys "{LEFT}"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
wscript.sleep 200
wshshell.sendkeys "%{UP}"
wscript.sleep 100
wshshell.sendkeys "%{UP}"
wscript.sleep 100
wshshell.sendkeys "%{UP}"
wscript.sleep 100
wshshell.sendkeys "M"
wscript.sleep 50
wshshell.sendkeys "R"
wscript.sleep 50
wshshell.sendkeys " "
wscript.sleep 50
wshshell.sendkeys "B"
wscript.sleep 50
wshshell.sendkeys "E"
wscript.sleep 50
wshshell.sendkeys "A"
wscript.sleep 50
wshshell.sendkeys "S"
wscript.sleep 50
wshshell.sendkeys "T"
wscript.sleep 50
wshshell.sendkeys "E"
wscript.sleep 50
wshshell.sendkeys "D"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
