start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
start msgbox1.vbs
:a
start msgbox2.vbs
goto a