Set WshShell = WScript.CreateObject("WScript.Shell")
WshShell.Run "notepad.exe", 9
wscript.sleep 2000
wshshell.sendkeys "Tu viens "
wscript.sleep 100
wshshell.sendkeys "d'installer "
wscript.sleep 100
wshshell.sendkeys "un vieux "
wscript.sleep 100
wshshell.sendkeys "virus de "
wscript.sleep 100
wshshell.sendkeys "al hmar "
wscript.sleep 100
wshshell.sendkeys "surgelle"
wscript.sleep 100
wshshell.sendkeys "."
wscript.sleep 1000
wshshell.sendkeys "{ENTER}"
wscript.sleep 100
wshshell.sendkeys "Toutes "
wscript.sleep 100
wshshell.sendkeys "t'es "
wscript.sleep 100
wshshell.sendkeys "donnees "
wscript.sleep 300
wshshell.sendkeys "et de "
wscript.sleep 100
wshshell.sendkeys "ceux "
wscript.sleep 100
wshshell.sendkeys "qui "
wscript.sleep 100
wshshell.sendkeys "sont "
wscript.sleep 100
wshshell.sendkeys "connectes "
wscript.sleep 400
wshshell.sendkeys "dans "
wscript.sleep 100
wshshell.sendkeys "le "
wscript.sleep 100
wshshell.sendkeys "meme "
wscript.sleep 100
wshshell.sendkeys "reseau "
wscript.sleep 100
wshshell.sendkeys "que "
wscript.sleep 100
wshshell.sendkeys "toi"
wscript.sleep 300
wshshell.sendkeys ","
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
wscript.sleep 1000
wshshell.sendkeys "seront "
wscript.sleep 100
wshshell.sendkeys "supprimes "
wscript.sleep 100
wshshell.sendkeys "au "
wscript.sleep 100
wshshell.sendkeys "prochain "
wscript.sleep 100
wshshell.sendkeys "demarrage "
wscript.sleep 100
wshshell.sendkeys "de "
wscript.sleep 150
wshshell.sendkeys "l'appareil."
wscript.sleep 2000
wshshell.sendkeys "^A"
wscript.sleep 100
wshshell.sendkeys "{BS}"
wscript.sleep 500
wshshell.sendkeys "B"
wscript.sleep 30
wshshell.sendkeys "o"
wscript.sleep 30
wshshell.sendkeys "n"
wscript.sleep 30
wshshell.sendkeys "n"
wscript.sleep 30
wshshell.sendkeys "e"
wscript.sleep 30
wshshell.sendkeys " "
wscript.sleep 30
wshshell.sendkeys "c"
wscript.sleep 30
wshshell.sendkeys "h"
wscript.sleep 30
wshshell.sendkeys "a"
wscript.sleep 30
wshshell.sendkeys "n"
wscript.sleep 30
wshshell.sendkeys "c"
wscript.sleep 30
wshshell.sendkeys "e"
wscript.sleep 30
wshshell.sendkeys " "
wscript.sleep 30
wshshell.sendkeys "p"
wscript.sleep 30
wshshell.sendkeys "o"
wscript.sleep 30
wshshell.sendkeys "u"
wscript.sleep 30
wshshell.sendkeys "r"
wscript.sleep 30
wshshell.sendkeys " "
wscript.sleep 30
wshshell.sendkeys "r"
wscript.sleep 30
wshshell.sendkeys "a"
wscript.sleep 30
wshshell.sendkeys "c"
wscript.sleep 30
wshshell.sendkeys "o"
wscript.sleep 30
wshshell.sendkeys "n"
wscript.sleep 30
wshshell.sendkeys "t"
wscript.sleep 30
wshshell.sendkeys "e"
wscript.sleep 30
wshshell.sendkeys "r"
wscript.sleep 30
wshshell.sendkeys " "
wscript.sleep 30
wshshell.sendkeys "l"
wscript.sleep 30
wshshell.sendkeys "a"
wscript.sleep 30
wshshell.sendkeys " "
wscript.sleep 30
wshshell.sendkeys "g"
wscript.sleep 30
wshshell.sendkeys "r"
wscript.sleep 30
wshshell.sendkeys "o"
wscript.sleep 30
wshshell.sendkeys "s"
wscript.sleep 30
wshshell.sendkeys "s"
wscript.sleep 30
wshshell.sendkeys "e"
wscript.sleep 30
wshshell.sendkeys " "
wscript.sleep 30
wshshell.sendkeys "b"
wscript.sleep 30
wshshell.sendkeys "e"
wscript.sleep 30
wshshell.sendkeys "t"
wscript.sleep 30
wshshell.sendkeys "i"
wscript.sleep 30
wshshell.sendkeys "s"
wscript.sleep 30
wshshell.sendkeys "e"
wscript.sleep 30
wshshell.sendkeys " "
wscript.sleep 30
wshshell.sendkeys "q"
wscript.sleep 30
wshshell.sendkeys "u"
wscript.sleep 30
wshshell.sendkeys "e"
wscript.sleep 30
wshshell.sendkeys " "
wscript.sleep 30
wshshell.sendkeys "t"
wscript.sleep 30
wshshell.sendkeys "u"
wscript.sleep 30
wshshell.sendkeys " "
wscript.sleep 30
wshshell.sendkeys "v"
wscript.sleep 30
wshshell.sendkeys "i"
wscript.sleep 30
wshshell.sendkeys "e"
wscript.sleep 30
wshshell.sendkeys "n"
wscript.sleep 30
wshshell.sendkeys "s"
wscript.sleep 30
wshshell.sendkeys " "
wscript.sleep 30
wshshell.sendkeys "d"
wscript.sleep 30
wshshell.sendkeys "e"
wscript.sleep 30
wshshell.sendkeys " "
wscript.sleep 30
wshshell.sendkeys "f"
wscript.sleep 30
wshshell.sendkeys "a"
wscript.sleep 30
wshshell.sendkeys "i"
wscript.sleep 30
wshshell.sendkeys "r"
wscript.sleep 30
wshshell.sendkeys "e"
wscript.sleep 30
wshshell.sendkeys " "
wscript.sleep 30
wshshell.sendkeys "a"
wscript.sleep 30
wshshell.sendkeys " "
wscript.sleep 30
wshshell.sendkeys "t"
wscript.sleep 30
wshshell.sendkeys "'"
wscript.sleep 30
wshshell.sendkeys "e"
wscript.sleep 30
wshshell.sendkeys "s"
wscript.sleep 30
wshshell.sendkeys " "
wscript.sleep 30
wshshell.sendkeys "p"
wscript.sleep 30
wshshell.sendkeys "a"
wscript.sleep 30
wshshell.sendkeys "r"
wscript.sleep 30
wshshell.sendkeys "e"
wscript.sleep 30
wshshell.sendkeys "n"
wscript.sleep 30
wshshell.sendkeys "t"
wscript.sleep 30
wshshell.sendkeys "s"
wscript.sleep 30
wshshell.sendkeys ","
wscript.sleep 500
wshshell.sendkeys "^A"
wshshell.sendkeys "{BS}"
wscript.sleep 500
wshshell.sendkeys "I"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "O"
wscript.sleep 1
wshshell.sendkeys "U"
wscript.sleep 1
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "I"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "O"
wscript.sleep 1
wshshell.sendkeys "U"
wscript.sleep 1
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "I"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "O"
wscript.sleep 1
wshshell.sendkeys "U"
wscript.sleep 1
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "I"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "O"
wscript.sleep 1
wshshell.sendkeys "U"
wscript.sleep 1
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "I"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "O"
wscript.sleep 1
wshshell.sendkeys "U"
wscript.sleep 1
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "I"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "O"
wscript.sleep 1
wshshell.sendkeys "U"
wscript.sleep 1
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "I"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "O"
wscript.sleep 1
wshshell.sendkeys "U"
wscript.sleep 1
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "I"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "O"
wscript.sleep 1
wshshell.sendkeys "U"
wscript.sleep 1
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "I"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "O"
wscript.sleep 1
wshshell.sendkeys "U"
wscript.sleep 1
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "I"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "O"
wscript.sleep 1
wshshell.sendkeys "U"
wscript.sleep 1
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "I"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "O"
wscript.sleep 1
wshshell.sendkeys "U"
wscript.sleep 1
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "I"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "O"
wscript.sleep 1
wshshell.sendkeys "U"
wscript.sleep 1
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "I"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "O"
wscript.sleep 1
wshshell.sendkeys "U"
wscript.sleep 1
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "I"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "O"
wscript.sleep 1
wshshell.sendkeys "U"
wscript.sleep 1
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "I"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "O"
wscript.sleep 1
wshshell.sendkeys "U"
wscript.sleep 1
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "I"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "O"
wscript.sleep 1
wshshell.sendkeys "U"
wscript.sleep 1
wshshell.sendkeys "{ENTER}"
wshshell.sendkeys "I"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "S"
wscript.sleep 1
wshshell.sendkeys "O"
wscript.sleep 1
wshshell.sendkeys "U"
wscript.sleep 10
wshshell.sendkeys "{ENTER}"
wscript.sleep 10
wshshell.sendkeys "{ENTER}"
wscript.sleep 10
wshshell.sendkeys "GZYM LE MEILLEUR"
wscript.sleep 10
wshshell.sendkeys "{ENTER}"
wscript.sleep 10
wshshell.sendkeys "#CPF"
wscript.sleep 100
wshshell.sendkeys "%{F4}"
wscript.sleep 100
wshshell.sendkeys "{LEFT}"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
wscript.sleep 200
wshshell.sendkeys "%{UP}"
wscript.sleep 100
wshshell.sendkeys "%{UP}"
wscript.sleep 100
wshshell.sendkeys "%{UP}"
wscript.sleep 100
wshshell.sendkeys "C"
wscript.sleep 50
wshshell.sendkeys "H"
wscript.sleep 50
wshshell.sendkeys "A"
wscript.sleep 50
wshshell.sendkeys "N"
wscript.sleep 50
wshshell.sendkeys "C"
wscript.sleep 50
wshshell.sendkeys "L"
wscript.sleep 50
wshshell.sendkeys "E"
wscript.sleep 50
wshshell.sendkeys "D"
wscript.sleep 100
wshshell.sendkeys "{ENTER}"
